# Site settings
title: Jonathan Martindell
email: jonmartindell@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Jonathan Martindell, a programmer living in Columbus Ohio.
  This is a simple blog about books I read and sometimes passing thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonmartindell.github.io" # the base hostname & protocol for your site
github_username:  jonmartindell

# Build settings
markdown: kramdown

gems: [octopress-debugger]
